-- Name: Raza Hamid
-- Roll Number: 26100319

-- Q1
SELECT
    C.FIRSTNAME,
    C.LASTNAME,
    C.ADDRESS,
    D.DIVISIONNAME,
    D.SUBDIVNAME,
    CT.DESCRIPTION,
    CONN.METERTYPE,
    B.IMPORT_PEAKUNITS,
    B.IMPORT_OFFPEAKUNITS,
    B.TOTALAMOUNT_BEFOREDUEDATE
FROM
         CUSTOMERS C
    JOIN CONNECTIONS     CONN ON C.CUSTOMERID = CONN.CUSTOMERID
    JOIN DIVINFO         D ON CONN.DIVISIONID = D.DIVISIONID
                      AND CONN.SUBDIVID = D.SUBDIVID
    JOIN CONNECTIONTYPES CT ON CONN.CONNECTIONTYPECODE = CT.CONNECTIONTYPECODE
    JOIN BILL            B ON CONN.CONNECTIONID = B.CONNECTIONID
WHERE
        B.BILLINGMONTH = 1
    AND B.BILLINGYEAR = 2024;


-- Q2
SELECT
    C.FIRSTNAME,
    C.LASTNAME,
    T.SLAB,
    CONN.CONNECTIONID,
    CT.CONNECTIONTYPECODE,
    CT.DESCRIPTION
FROM
         CUSTOMERS C
    JOIN CONNECTIONS     CONN ON C.CUSTOMERID = CONN.CUSTOMERID
    JOIN CONNECTIONTYPES CT ON CONN.CONNECTIONTYPECODE = CT.CONNECTIONTYPECODE
    JOIN TARIFF          T ON CT.CONNECTIONTYPECODE = T.CONNECTIONTYPECODE
    JOIN BILL            B ON CONN.CONNECTIONID = B.CONNECTIONID
WHERE
        B.BILLINGMONTH = 3
    AND B.BILLINGYEAR = 2024
    AND B.TOTALAMOUNT_BEFOREDUEDATE >= 100000;


-- Q3
SELECT
    C.FIRSTNAME,
    C.LASTNAME,
    T.SLAB,
    CONN.CONNECTIONID,
    CT.CONNECTIONTYPECODE,
    CT.DESCRIPTION
FROM
         CUSTOMERS C
    JOIN CONNECTIONS     CONN ON C.CUSTOMERID = CONN.CUSTOMERID
    JOIN CONNECTIONTYPES CT ON CONN.CONNECTIONTYPECODE = CT.CONNECTIONTYPECODE
    JOIN TARIFF          T ON CT.CONNECTIONTYPECODE = T.CONNECTIONTYPECODE
    JOIN BILL            B ON CONN.CONNECTIONID = B.CONNECTIONID
WHERE
    B.BILLINGMONTH BETWEEN 1 AND 6
    AND B.BILLINGYEAR = 2024
    AND B.SUBSIDYAMOUNT > 0
GROUP BY
    C.FIRSTNAME,
    C.LASTNAME,
    T.SLAB,
    CONN.CONNECTIONID,
    CT.CONNECTIONTYPECODE,
    CT.DESCRIPTION
HAVING
    COUNT(DISTINCT B.BILLINGMONTH) >= 2;


-- Q4
SELECT
    C.FIRSTNAME,
    C.LASTNAME,
    CONN.CONNECTIONID,
    B.BILLID,
    B.BILLINGMONTH,
    B.BILLINGYEAR,
    P.AMOUNTPAID,
    B.TOTALAMOUNT_BEFOREDUEDATE
FROM
         CUSTOMERS C
    JOIN CONNECTIONS    CONN ON C.CUSTOMERID = CONN.CUSTOMERID
    JOIN BILL           B ON CONN.CONNECTIONID = B.CONNECTIONID
    LEFT JOIN PAYMENTDETAILS P ON B.BILLID = P.BILLID
WHERE
    ( P.AMOUNTPAID IS NULL
      OR P.AMOUNTPAID < B.TOTALAMOUNT_BEFOREDUEDATE );


-- Q5
SELECT
    D.SUBDIVNAME,
    CT.DESCRIPTION
FROM
         DIVINFO D
    JOIN CONNECTIONS     CONN ON D.DIVISIONID = CONN.DIVISIONID
                             AND D.SUBDIVID = CONN.SUBDIVID
    JOIN CONNECTIONTYPES CT ON CONN.CONNECTIONTYPECODE = CT.CONNECTIONTYPECODE
WHERE
    CT.DESCRIPTION LIKE 'Industry%'



-- Q6
SELECT
    S.SUBSIDYDESCRIPTION
FROM
         BILL B
    JOIN CONNECTIONS CONN ON B.CONNECTIONID = CONN.CONNECTIONID
WHERE
    CONN.CONNECTIONTYPECODE IN ( 1, 2, 3 )
    AND B.BILLINGMONTH = 6
    AND B.BILLINGYEAR = 2024;


-- Q7
SELECT
    C.FIRSTNAME,
    C.LASTNAME,
    CONN.CONNECTIONID,
    CT.CONNECTIONTYPECODE,
    CT.DESCRIPTION
FROM
         CUSTOMERS C
    JOIN CONNECTIONS     CONN ON C.CUSTOMERID = CONN.CUSTOMERID
    JOIN CONNECTIONTYPES CT ON CONN.CONNECTIONTYPECODE = CT.CONNECTIONTYPECODE
    JOIN BILL            B ON CONN.CONNECTIONID = B.CONNECTIONID
WHERE
        B.BILLINGMONTH = 5
    AND B.BILLINGYEAR = 2024
ORDER BY
    B.TOTALAMOUNT_BEFOREDUEDATE DESC
FETCH FIRST 1 ROWS ONLY;


-- Q8
SELECT
    COUNT(DISTINCT C.CUSTOMERID) AS TOTALRESIDENTIALCUSTOMERS
FROM
         CUSTOMERS C
    JOIN CONNECTIONS CONN ON C.CUSTOMERID = CONN.CUSTOMERID
    JOIN BILL        B ON CONN.CONNECTIONID = B.CONNECTIONID
WHERE
    CONN.CONNECTIONTYPECODE IN ( 1, 2, 3 )
    AND B.SUBSIDYAMOUNT > 0
    AND B.BILLINGMONTH = 6
    AND B.BILLINGYEAR = 2024;


-- Q9
SELECT
    D.DIVISIONNAME,
    D.SUBDIVNAME,
    COUNT(DISTINCT C.CUSTOMERID) AS TOTALCOMMERCIALCUSTOMERS
FROM
         CUSTOMERS C
    JOIN CONNECTIONS CONN ON C.CUSTOMERID = CONN.CUSTOMERID
    JOIN DIVINFO     D ON CONN.DIVISIONID = D.DIVISIONID
                      AND CONN.SUBDIVID = D.SUBDIVID
    JOIN BILL        B ON CONN.CONNECTIONID = B.CONNECTIONID
WHERE
    CONN.CONNECTIONTYPECODE IN ( 11, 12, 13, 14, 15,
                                 16 )
    AND B.BILLINGMONTH = 3
    AND B.BILLINGYEAR = 2024
    AND B.TOTALAMOUNT_BEFOREDUEDATE >= 500000
GROUP BY
    D.DIVISIONNAME,
    D.SUBDIVNAME
ORDER BY
    D.DIVISIONNAME,
    D.SUBDIVNAME;


-- Q10
SELECT
    D.DIVISIONNAME,
    D.SUBDIVNAME,
    SUM(B.TAXAMOUNT) AS TOTALTAXAMOUNT
FROM
         DIVINFO D
    JOIN CONNECTIONS CONN ON D.DIVISIONID = CONN.DIVISIONID
                             AND D.SUBDIVID = CONN.SUBDIVID
    JOIN BILL        B ON CONN.CONNECTIONID = B.CONNECTIONID
WHERE
        B.BILLINGMONTH = 8
    AND B.BILLINGYEAR = 2024
GROUP BY
    D.DIVISIONNAME,
    D.SUBDIVNAME;



-- Q11
SELECT
    D.DIVISIONNAME,
    D.SUBDIVNAME,
    SUM(B.TAXAMOUNT) AS TOTALTAXRECEIVED
FROM
         DIVINFO D
    JOIN CONNECTIONS    CONN ON D.DIVISIONID = CONN.DIVISIONID
                             AND D.SUBDIVID = CONN.SUBDIVID
    JOIN BILL           B ON CONN.CONNECTIONID = B.CONNECTIONID
    JOIN PAYMENTDETAILS PD ON B.BILLID = PD.BILLID
WHERE
        PD.AMOUNTPAID >= B.TOTALAMOUNTBEFOREDUEDATE
    AND B.BILLINGMONTH = 8
    AND B.BILLINGYEAR = 2024
GROUP BY
    D.DIVISIONNAME,
    D.SUBDIVNAME;


-- Q12
SELECT
    CT.CONNECTIONTYPECODE,
    CT.DESCRIPTION,
    COUNT(DISTINCT C.CUSTOMERID) AS TOTALCUSTOMERSWITHSUBSIDY
FROM
         CONNECTIONTYPES CT
    JOIN CONNECTIONS CONN ON CT.CONNECTIONTYPECODE = CONN.CONNECTIONTYPECODE
    JOIN CUSTOMERS   C ON CONN.CUSTOMERID = C.CUSTOMERID
    JOIN BILL        B ON CONN.CONNECTIONID = B.CONNECTIONID
WHERE
        B.SUBSIDYAMOUNT > 0
    AND B.BILLINGMONTH = 6
    AND B.BILLINGYEAR = 2024
GROUP BY
    CT.CONNECTIONTYPECODE,
    CT.DESCRIPTION;



-- Q13
WITH RANKEDCUSTOMERS AS (
    SELECT
        D.DIVISIONNAME,
        D.SUBDIVNAME,
        C.FIRSTNAME,
        C.LASTNAME,
        CONN.CONNECTIONID,
        CT.CONNECTIONTYPECODE,
        CT.DESCRIPTION,
        B.TOTALAMOUNT_BEFOREDUEDATE,
        ROW_NUMBER()
        OVER(PARTITION BY D.DIVISIONNAME, D.SUBDIVNAME
             ORDER BY
                 B.TOTALAMOUNT_BEFOREDUEDATE DESC
        ) AS RANK
    FROM
             DIVINFO D
        JOIN CONNECTIONS     CONN ON D.DIVISIONID = CONN.DIVISIONID
                                 AND D.SUBDIVID = CONN.SUBDIVID
        JOIN CUSTOMERS       C ON CONN.CUSTOMERID = C.CUSTOMERID
        JOIN CONNECTIONTYPES CT ON CONN.CONNECTIONTYPECODE = CT.CONNECTIONTYPECODE
        JOIN BILL            B ON CONN.CONNECTIONID = B.CONNECTIONID
    WHERE
        CONN.CONNECTIONTYPECODE IN ( 1, 2, 3 )
        AND B.BILLINGMONTH = 6
        AND B.BILLINGYEAR = 2024
)
SELECT
    DIVISIONNAME,
    SUBDIVNAME,
    FIRSTNAME,
    LASTNAME,
    CONNECTIONID,
    CONNECTIONTYPECODE,
    DESCRIPTION,
    TOTALAMOUNT_BEFOREDUEDATE
FROM
    RANKEDCUSTOMERS
WHERE
    RANK = 1;



-- Q14
WITH SUBDIVISIONTAX AS (
    SELECT
        D.DIVISIONNAME,
        D.SUBDIVNAME,
        SUM(B.TAXAMOUNT) AS TOTALTAXAMOUNT
    FROM
             DIVINFO D
        JOIN CONNECTIONS CONN ON D.DIVISIONID = CONN.DIVISIONID
                                 AND D.SUBDIVID = CONN.SUBDIVID
        JOIN BILL        B ON CONN.CONNECTIONID = B.CONNECTIONID
    WHERE
            D.DIVISIONNAME = 'Lahore'
        AND B.BILLINGMONTH = 6
        AND B.BILLINGYEAR = 2024
    GROUP BY
        D.DIVISIONNAME,
        D.SUBDIVNAME
)
SELECT
    SUBDIVNAME,
    TOTALTAXAMOUNT
FROM
    SUBDIVISIONTAX
ORDER BY
    TOTALTAXAMOUNT DESC
FETCH FIRST 1 ROWS ONLY;


-- Q15
WITH PEAKCONSUMPTION AS (
    SELECT
        C.FIRSTNAME,
        C.LASTNAME,
        CONN.CONNECTIONID,
        CT.CONNECTIONTYPECODE,
        CT.DESCRIPTION,
        SUM(B.IMPORT_PEAKUNITS) AS TOTALPEAKUNITS
    FROM
             CUSTOMERS C
        JOIN CONNECTIONS     CONN ON C.CUSTOMERID = CONN.CUSTOMERID
        JOIN CONNECTIONTYPES CT ON CONN.CONNECTIONTYPECODE = CT.CONNECTIONTYPECODE
        JOIN BILL            B ON CONN.CONNECTIONID = B.CONNECTIONID
    WHERE
        CONN.CONNECTIONTYPECODE IN ( 1, 2, 3 )
        AND B.BILLINGMONTH IN ( 6, 7, 8 )
        AND B.BILLINGYEAR = 2024
    GROUP BY
        C.FIRSTNAME,
        C.LASTNAME,
        CONN.CONNECTIONID,
        CT.CONNECTIONTYPECODE,
        CT.DESCRIPTION
)
SELECT
    FIRSTNAME,
    LASTNAME,
    CONNECTIONID,
    CONNECTIONTYPECODE,
    DESCRIPTION,
    TOTALPEAKUNITS
FROM
    PEAKCONSUMPTION
ORDER BY
    TOTALPEAKUNITS DESC
FETCH FIRST 1 ROWS ONLY;


-- Q16
WITH AVGBILLJANTOJULY AS (
    SELECT
        CONN.CUSTOMERID,
        CONN.CONNECTIONID,
        AVG(B.TOTALAMOUNT_BEFOREDUEDATE) AS AVGBILL
    FROM
             CONNECTIONS CONN
        JOIN BILL B ON CONN.CONNECTIONID = B.CONNECTIONID
    WHERE
        B.BILLINGMONTH BETWEEN 1 AND 7
        AND B.BILLINGYEAR = 2024
    GROUP BY
        CONN.CUSTOMERID,
        CONN.CONNECTIONID
), CURRENTBILLAUGUST AS (
    SELECT
        CONN.CUSTOMERID,
        CONN.CONNECTIONID,
        B.TOTALAMOUNT_BEFOREDUEDATE AS AUGUSTBILL
    FROM
             CONNECTIONS CONN
        JOIN BILL B ON CONN.CONNECTIONID = B.CONNECTIONID
    WHERE
            B.BILLINGMONTH = 8
        AND B.BILLINGYEAR = 2024
)
SELECT
    C.FIRSTNAME,
    C.LASTNAME,
    CONN.CONNECTIONID,
    CT.CONNECTIONTYPECODE,
    CT.DESCRIPTION
FROM
         CUSTOMERS C
    JOIN CONNECTIONS       CONN ON C.CUSTOMERID = CONN.CUSTOMERID
    JOIN CONNECTIONTYPES   CT ON CONN.CONNECTIONTYPECODE = CT.CONNECTIONTYPECODE
    JOIN AVGBILLJANTOJULY  AB ON CONN.CONNECTIONID = AB.CONNECTIONID
    JOIN CURRENTBILLAUGUST CB ON CONN.CONNECTIONID = CB.CONNECTIONID
WHERE
    CB.AUGUSTBILL < ( AB.AVGBILL / 2 );